- hosts: all
  roles:
    - role: fetch-sphinx-tarball
      sphinx_output_suffix: "/"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - role: upload-otc-docs
      when: zuul_success | bool
