- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.zuul.tsi-dev.otc-service.com"

- hosts: all
  pre_tasks:
    # NOTE(pabelanger): Until we hit the validate-host role, we have a minimal
    # set of ansible variables collected by zuul-executor. This doesn't include
    # network variables (ansible_default_ipv4 / ansible_default_ipv6) so gather
    # these variables as they are important to the configure-unbound role.
    - name: Gather network facts
      setup:
        gather_subset: 'network'

  roles:
    - add-build-sshkey
    - start-zuul-console
    - validate-host
    - use-cached-repos
    - mirror-workspace-git-repos
    # - role: fetch-zuul-cloner
    #   destination: "/usr/zuul-env/bin/zuul-cloner"
    #   repo_src_dir: "/home/zuul/src/git.openstack.org"
