- hosts: localhost
  tasks:
    # TODO:
    # - clean the resources, which might have been created
    # - revoke the temp token explicitely
    - name: read token
      delegate_to: localhost
      set_fact:
        token_data: "{{ lookup('file', zuul.executor.work_root + '/.' +  zuul.build)"
      no_log: true

    - name: delete data file
      file:
        path: "{{ zuul.executor.work_root }}/.{{ zuul.build }}"
        state: absent

    - include_role:
        name: revoke_token
      vars:
        cloud: "{{ functest_cloud_config }}"
        token: "{{ token_data }}"
