- hosts: localhost
  tasks:
    # TODO:
    # - clean the resources, which might have been created
    # - revoke the temp token explicitely

    - include_role:
        name: revoke_token
      vars:
        cloud: "{{ functest_cloud_config }}"
        token: "{{ job_token }}"
