- hosts: all
  tasks:
    - name: Get temporary token
      os_auth:
        cloud:
          profile: "{{ functest_cloud_config.profile | default(omit) }}"
          auth:
            auth_url: "{{ functest_cloud_config.auth.auth_url }}"
            username: "{{ functest_cloud_config.auth.username }}"
            password: "{{ functest_cloud_config.auth.password }}"
            user_domain_name: "{{ functest_cloud_config.auth.user_domain_name | default(omit) }}"
            user_domain_id: "{{ functest_cloud_config.auth.user_domain_id | default(omit) }}"
            domain_name: "{{ functest_cloud_config.auth.domain_name | default(omit) }}"
            domain_id: "{{ functest_cloud_config.auth.domain_id | default(omit) }}"
            project_name: "{{ functest_project_name | default(functest_cloud_config.auth.project_name) | default(omit) }}"
      register: os_auth
      delegate_to: localhost

    - name: Verify token
      os_auth:
        cloud:
          profile: "{{ functest_cloud_config.profile | default(omit) }}"
          auth_type: token
          auth:
            auth_url: "{{ functest_cloud_config.auth.auth_url }}"
            token: "{{ os_auth.ansible_facts.auth_token }}"
            project_name: "{{ functest_project_name | default(functest_cloud_config.auth.project_name) | default(omit) }}"
      delegate_to: localhost

    - name: Include deploy-clouds-config role
      include_role:
        name: deploy-clouds-config
      vars:
        cloud_config:
          clouds:
            functest_cloud:
              profile: "{{ functest_cloud_config.profile | default(omit) }}"
              auth_type: token
              auth:
                auth_url: "{{ functest_cloud_config.auth.auth_url | default(omit) }}"
                # project_name: "{{ functest_cloud_config.auth.project_name }}"
                project_name: "{{ functest_project_name | default(functest_cloud_config.auth.project_name) | default(omit) }}"
                token: "{{ os_auth.ansible_facts.auth_token }}"

    - name: Save token
      delegate_to: localhost
      copy:
        dest: "{{ zuul.executor.work_root }}/.{{ zuul.build }}"
        content: "{{ os_auth.ansible_facts.auth_token }}"
        mode: "0440"
